spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samsong8610/spring-cloud-demo-config.git

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
