spring:
  application:
    name: portal-server
  thymeleaf:
    mode: LEGACYHTML5
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0 # Sampling all requests
  cloud:
    config:
      uri: http://localhost:5555
server:
  contextPath: /portal
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#    registerWithEureka: false

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
